[tool.black]
line-length = 150
target-version = ['py310']
exclude = '''
/(
  | migrations
)/

'''

[tool.isort]
profile = "black"
skip = "migrations"

[tool.ruff]
line-length = 150
target-version = "py310"
exclude = ["migrations"]

[tool.codespell]
skip = "redis.conf,*.pyc"
ignore-words-list = "corus"
quiet-level = 2
